### ISSUE TITLE
Sign up form Name fields should specify Legal name

### ISSUE THREAD

**Issue by ginnyfahs** [bocoup/ccpa-authorized-agent#21]
I found myself filling out the name fields in the sign up form as Ginny, even though my full legal name is Virginia.

Can we change `First Name` to be `Legal First Name`?

**Comment by alflennik** [comment]
<img width="688" alt="Screen Shot 2021-02-05 at 11 08 44 AM" src="https://user-images.githubusercontent.com/5255858/107058367-847bc980-67a2-11eb-8cad-0f1fb9f55a55.png">
Hi @ginnyfahs, that's a great idea. This will be in the next release. Note I updated both the first name and last name because it looks more symmetrical that way.

**Comment by jesdaigle** [comment]
Fixed
